name: Deploy static content to S3

on:
  push:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop
      - uses: pnpm/action-setup@v2
        with: 
          version: 8
      - run: pnpm install
        working-directory: ./app
      - run: pnpm run build
        env:
          GENERATE_SOURCEMAP: ${{ vars.GENERATE_SOURCEMAP }}
          VITE_ADDRESS: ${{ vars.REACT_APP_ADDRESS }}
          VITE_AUTH_COOKIE_STORAGE_DOMAIN: ${{ vars.REACT_APP_AUTH_COOKIE_STORAGE_DOMAIN }}
          VITE_ETHEREUM_API: ${{ secrets.REACT_APP_ETHEREUM_API }}
          VITE_POLYGON_API: ${{ secrets.REACT_APP_POLYGON_API }}
          VITE_SOLANA_API: ${{ secrets.REACT_APP_SOLANA_API }}
          VITE_SOLANA_SECRET_KEY: ${{ secrets.REACT_APP_SOLANA_SECRET_KEY }}
          VITE_AUTH_REGION: ${{ secrets.REACT_APP_AUTH_REGION }}
          VITE_AUTH_USER_POOL_ID: ${{ secrets.REACT_APP_AUTH_USER_POOL_ID }}
          VITE_AUTH_USER_POOL_WEB_CLIENT_ID: ${{ secrets.REACT_APP_AUTH_USER_POOL_WEB_CLIENT_ID }}
          VITE_ETHERSCAN_API_KEY: ${{ secrets.VITE_ETHERSCAN_API_KEY }}
          VITE_POLYGONSCAN_API_KEY: ${{ secrets.VITE_POLYGONSCAN_API_KEY }}
        working-directory: ./app
      - name: Configure AWS credentials with IAM Role
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{vars.AWS_ROLENAME}}
          aws-region: ${{vars.AWS_REGION}}
      - name: Copy files to S3
        run: |
            aws s3 sync ./app/dist s3://${{vars.AWS_S3_BUCKET}}
